[metadata]
name = laplskel
url = https://github.com/smoia/laplskel
download_url = https://github.com/smoia/laplskel
author = Stefano Moia
maintainer = Stefano Moia
maintainer_email = s.moia.research@gmail.com
classifiers =
    Development Status :: 4 - Beta
    Intended Audience :: Science/Research
    License :: OSI Approved :: Apache Software License
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11
    Programming Language :: Python :: 3.12
    Programming Language :: Python :: 3.13
license = Apache-2.0
description = An attempt to render in a function-oriented library Damseh 2021's algorithm - plus some more.
long_description = file:README.md
long_description_content_type = text/markdown; charset=UTF-8
platforms = OS Independent
provides =
    laplskel

[options]
python_requires = >=3.10
install_requires =
    duecredit
    joblib
    nibabel
    nigsp
    numpy>=1.17
    scipy>=1.14.1
    tqdm_joblib
tests_require =
    pytest >=8.0
test_suite = pytest
zip_safe = False
packages = find:
include_package_data = True

[options.extras_require]
style =
    codespell>=2.2.4
    ruff>=0.14.2
test =
    %(style)s
    pytest>=8.0
    pytest-cov
    coverage
devtools =
    pre-commit
dev =
    %(devtools)s
    %(test)s

[options.entry_points]
console_scripts =
    laplskel=laplskel:_main

[codespell]
skip = versioneer.py,.git,build,./docs/_build
ignore-words-list = nd,commun
write-changes =
count =
quiet-level = 3

[tool:pytest]
doctest_optionflags = NORMALIZE_WHITESPACE
xfail_strict = true
addopts = -rx

[versioneer]
VCS = git
style = pep440
versionfile_source = laplskel/_version.py
versionfile_build = laplskel/_version.py
tag_prefix =
parentdir_prefix =
