"""High-level skeletonisation pipeline."""

import numpy as np
from scipy import sparse

from .components import label_and_sort_by_size
from .image_io import (
    coords_to_dense_3d,
    get_output_path,
    load_nifti_mask,
    save_skeleton,
)
from .runtime import process_components
from .solvers import validate_solver


def laplacian_skeletonisation(
    nifti_path,
    out_path=None,
    use_edt=True,
    use_anisotropic=True,
    enforce_containment=False,
    beta_edt=1.0,
    w_L=0.5,
    w_H_base=0.5,
    tol=0.05,
    decimate_every=1,
    min_edge_length=0.01,
    downsample=False,
    seed=42,
    separate_streams=False,
    label_connectivity=6,
    max_distance=2.4999,
    n_jobs=None,
    graphml=False,
    solver='CG',
):
    """
    Load a NIfTI file volume image and perform geometric graph contraction skeletonisation.

    Parameters
    ----------
    nifti_path : str
        File system location path pointing directly toward the source input .nii or .nii.gz file.
    out_path : str, optional
        Output destination storage path base where resulting arrays and generated skeleton
        files will be written. Default is None (autogenerated from input file name).
    use_edt : bool, optional
        Enables boundary tracking potential constraints using Euclidean Distance Transforms.
        Default is True.
    use_anisotropic : bool, optional
        Enables anisotropic geometry handling to penalize internal longitudinal
        shortening vectors. Default is True.
    enforce_containment : bool, optional
        If True, applies a hard projection constraint to force nodes drifting out of the
        foreground mask onto the closest inner boundary shell surface voxel.
        Default is False.
    beta_edt : float, optional
        Scaling modulation weight assigned to boundary energy calculation properties.
        Default is 1.0.
    w_L : float, optional
        Contraction weight step modifier targeting structural local geometric collapse.
        This should be alpha in Damseh 2021. Default is 0.5.
    w_H_base : float, optional
        Baseline structural node anchor positional persistence value metric.
        This should be equivalent to beta in Damseh 2021. Default is 0.5.
    tol : float, optional
        Convergence tolerance limit evaluated against mean vertex displacement.
        This should be the equivalent of gamma in Damseh 2021 (not sure). Default is 0.05.
    decimate_every : int, optional
        Frequency cadence interval defining how many contraction loop steps occur before
        triggering an edge-collapse decimation execution. Default is 1.
    min_edge_length : float, optional
        The Euclidean spatial threshold criteria below which two connected nodes undergo
        structural merging, i.e. the isotropic voxel size of the grid used for
        decimation. Default is 0.01.
    downsample : bool, optional
        Flag setting whether point arrays containing high density are uniformly downsampled
        to stay within safe RAM footprints. Default is False.
    seed : int, optional
        Base random seed for reproducible downsampling (42 is default).
    separate_streams : bool, optional
        Process each "independent" vessel by itself (i.e. non-connected segment)
    label_connectivity : 6, 18, 26, optional
        Connectivity profile to use to separate streams - 6, 18, or 26 edges.
    max_distance : float
        Maximum distance to consider when making the sparse adjacency matrix.
    n_jobs : None, optional
        Number of parallel jobs. If not set or <=0, defaults to ~30%% of available CPU
        cores.
    graphml : bool, optional
        Write the converged graph as GraphML instead of coordinate and adjacency
        NPZ files. The dense NIfTI skeleton is still written. Default is False.
    solver : {'LU', 'CG', 'AMGCG'}, optional
        Linear-system solver used by the contraction loop. Default is CG.

    Returns
    -------
    contracted_X : numpy.ndarray
        An (M, 3) matrix mapping the continuous 3D spatial points along the skeleton path.
    final_adj : scipy.sparse.csr_matrix
        The resulting graph sparse adjacency connectivity representation of shape (M, M).
    nifti_skel : numpy.ndarray
        A dense nifti matrix with the skeleton inside.

    Raises
    ------
    ValueError
        If the loaded structural NIfTI mask image is completely empty or lacks foreground elements.
    """
    solver = validate_solver(solver)
    print(f'Ingesting NIfTI image: {nifti_path}')
    _, volume_data, img = load_nifti_mask(nifti_path)

    if not np.any(volume_data):
        raise ValueError('Provided segmentation volume lacks any foreground structure.')

    # Downsample points cloud initialization limits if necessary to guard RAM bounds
    if downsample and np.any(volume_data) > 200000:
        print(f'Volume contains {np.any(volume_data)} points. Downsampling.')
        vessel_voxels = np.argwhere(volume_data).astype(np.uint16)
        rng = np.random.default_rng(seed=seed)
        idx = rng.choice(len(vessel_voxels), 150000, replace=False)
        vessel_voxels = vessel_voxels[idx]
        volume_data = coords_to_dense_3d(vessel_voxels, volume_data.shape)

    # Process each component independently if separate_streams is True
    if separate_streams:
        labeled_volume, num_features = label_and_sort_by_size(
            volume_data, label_connectivity
        )
    else:
        labeled_volume, num_features = volume_data * 1, 1

    results = process_components(
        labeled_volume,
        num_features,
        use_edt,
        use_anisotropic,
        enforce_containment,
        beta_edt,
        w_L,
        w_H_base,
        tol,
        max_distance,
        decimate_every,
        min_edge_length,
        n_jobs,
        solver,
    )

    print('Reuniting results from parallel jobs.')

    if not results:
        raise ValueError('No valid components found for contraction.')

    # Merge coordinates and sparse block-diagonal adjacency matrices across all labels
    contracted_X = np.vstack([res[1] for res in results])
    final_adj = sparse.block_diag([res[2] for res in results], format='csr')
    component_labels = np.concatenate(
        [np.full(res[1].shape[0], res[0], dtype=int) for res in results]
    )

    out_path = get_output_path(nifti_path, out_path)
    nifti_skel = save_skeleton(
        out_path,
        contracted_X,
        final_adj,
        volume_data,
        img,
        enforce_containment,
        graphml=graphml,
        component_labels=component_labels,
    )

    return contracted_X, final_adj, nifti_skel
